"use client";

import { Sparkles } from "lucide-react";

export default function AIInsights() {
  return (
    <div className="rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-950/40 to-slate-900 p-6">
      <div className="flex items-center gap-3">
        <div className="rounded-2xl bg-violet-600 p-3">
          <Sparkles className="text-white" size={24} />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-white">
            AI Interview Feedback
          </h2>

          <p className="text-slate-400">
            Personalized feedback generated by AI.
          </p>
        </div>
      </div>

      <div className="mt-6 space-y-4 text-slate-300">

        <p>
          ✅ You demonstrated a solid understanding of core programming concepts.
        </p>

        <p>
          ✅ Your answers were well structured and easy to follow.
        </p>

        <p>
          ⚠ Improve confidence while explaining your approach.
        </p>

        <p>
          ⚠ Practice Dynamic Programming and System Design questions regularly.
        </p>

        <p className="rounded-xl border border-green-500/20 bg-green-500/10 p-4 text-green-300">
          Hiring Recommendation: <strong>Recommended for the Next Round</strong>
        </p>

      </div>
    </div>
  );
}