"use client";

import { useRef, useState } from "react";
import {
  UploadCloud,
  FileText,
  X,
  Sparkles,
  ShieldCheck,
  FileSearch,
} from "lucide-react";
import { motion } from "framer-motion";
import ResumeAnalysis from "./ResumeAnalysis";

export default function ResumeUpload() {
  const inputRef = useRef<HTMLInputElement>(null);

  const [file, setFile] = useState<File | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<any>(null);

  const MAX_SIZE = 5 * 1024 * 1024;

  const handleFile = (selectedFile: File) => {
    setError("");
    setAnalysis(null);

    const validTypes = [
      "application/pdf",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ];

    if (!validTypes.includes(selectedFile.type)) {
      setError("Only PDF and DOCX files are allowed.");
      return;
    }

    if (selectedFile.size > MAX_SIZE) {
      setError("File size must be less than 5 MB.");
      return;
    }

    setFile(selectedFile);
  };

  const removeFile = () => {
    setFile(null);
    setAnalysis(null);
    setError("");

    if (inputRef.current) {
      inputRef.current.value = "";
    }
  };

  const analyzeResume = async () => {
    if (!file) return;

    try {
      setLoading(true);
      setError("");
      setAnalysis(null);

      const formData = new FormData();
      formData.append("file", file);

      const response = await fetch("http://127.0.0.1:8000/analyze", {
        method: "POST",
        body: formData,
      });

      const text = await response.text();
      const data = JSON.parse(text);

      if (data.success) {
        setAnalysis(data.analysis);
      } else {
        setError(data.error || data.message || "Analysis failed");
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 25 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="relative overflow-hidden rounded-3xl border border-slate-700/50 bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 shadow-2xl"
    >
      {/* Glow */}
      <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-indigo-600/20 blur-3xl" />
      <div className="absolute -left-24 -bottom-24 h-72 w-72 rounded-full bg-cyan-500/20 blur-3xl" />

      <div className="relative p-10">

        {!file ? (

          <div className="text-center">

            <div className="mx-auto flex h-24 w-24 items-center justify-center rounded-3xl bg-gradient-to-br from-indigo-600 to-cyan-500 shadow-xl shadow-indigo-500/40">

              <UploadCloud className="h-12 w-12 text-white" />

            </div>

            <div className="mt-8 inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-2 text-sm text-indigo-300">

              <Sparkles size={16} />

              AI Powered Resume Scanner

            </div>

            <h1 className="mt-6 text-5xl font-bold text-white">

              Upload Your Resume

            </h1>

            <p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-400">

              Get ATS Score, Placement Readiness, Missing Skills,
              AI Suggestions and Personalized Career Roadmap in
              just a few seconds.

            </p>

            <div className="mt-10 grid gap-5 md:grid-cols-3">

              <div className="rounded-2xl border border-slate-700 bg-slate-900/70 p-6">

                <ShieldCheck className="mx-auto mb-4 h-10 w-10 text-emerald-400" />

                <h3 className="font-semibold text-white">
                  ATS Optimized
                </h3>

                <p className="mt-2 text-sm text-slate-400">
                  Analyze your resume against modern ATS systems.
                </p>

              </div>

              <div className="rounded-2xl border border-slate-700 bg-slate-900/70 p-6">

                <Sparkles className="mx-auto mb-4 h-10 w-10 text-indigo-400" />

                <h3 className="font-semibold text-white">
                  AI Suggestions
                </h3>

                <p className="mt-2 text-sm text-slate-400">
                  Personalized improvements generated by AI.
                </p>

              </div>

              <div className="rounded-2xl border border-slate-700 bg-slate-900/70 p-6">

                <FileSearch className="mx-auto mb-4 h-10 w-10 text-cyan-400" />

                <h3 className="font-semibold text-white">
                  Skill Gap Report
                </h3>

                <p className="mt-2 text-sm text-slate-400">
                  Find missing skills required for placements.
                </p>

              </div>

            </div>

                        <input
              ref={inputRef}
              type="file"
              accept=".pdf,.docx"
              className="hidden"
              onChange={(e) => {
                if (e.target.files?.length) {
                  handleFile(e.target.files[0]);
                }
              }}
            />

            <button
              onClick={() => inputRef.current?.click()}
              className="mt-10 rounded-2xl bg-gradient-to-r from-indigo-600 to-cyan-500 px-10 py-4 text-lg font-semibold text-white shadow-lg shadow-indigo-500/30 transition duration-300 hover:scale-105 hover:shadow-indigo-500/50"
            >
              Choose Resume
            </button>

            <p className="mt-5 text-sm text-slate-500">
              Supported formats: PDF, DOCX • Maximum Size: 5 MB
            </p>

            {error && (
              <div className="mt-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">
                {error}
              </div>
            )}

          </div>

        ) : (

          <motion.div
            initial={{ opacity: 0, scale: .96 }}
            animate={{ opacity: 1, scale: 1 }}
            className="rounded-3xl border border-slate-700 bg-slate-900/80 p-8 backdrop-blur-xl"
          >

            <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

              <div className="flex items-center gap-5">

                <div className="rounded-2xl bg-indigo-500/10 p-4">

                  <FileText className="h-10 w-10 text-indigo-400" />

                </div>

                <div>

                  <h2 className="text-xl font-bold text-white">

                    {file.name}

                  </h2>

                  <p className="mt-1 text-slate-400">

                    {(file.size / (1024 * 1024)).toFixed(2)} MB

                  </p>

                </div>

              </div>

              <button
                onClick={removeFile}
                className="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-red-400 transition hover:bg-red-500/20"
              >
                <X />
              </button>

            </div>

            <button
              onClick={analyzeResume}
              disabled={loading}
              className="mt-8 w-full rounded-2xl bg-gradient-to-r from-emerald-500 via-green-500 to-emerald-600 py-4 text-lg font-bold text-white shadow-lg shadow-emerald-500/30 transition duration-300 hover:scale-[1.02] disabled:cursor-not-allowed disabled:opacity-60"
            >

              {loading ? (

                <div className="flex items-center justify-center gap-3">

                  <div className="h-6 w-6 animate-spin rounded-full border-2 border-white border-t-transparent" />

                  <span>AI is analyzing your resume...</span>

                </div>

              ) : (

                "Analyze Resume"

              )}

            </button>

            {error && (

              <div className="mt-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-center text-red-300">

                {error}

              </div>

            )}

            {analysis && (

              <ResumeAnalysis analysis={analysis} />

            )}

          </motion.div>

        )}

      </div>

          </motion.div>
  );
}